### ISSUE TITLE
Conflicts with DMSF hook

### ISSUE THREAD

**Issue by tsz662** [tsz662/redmine_amazon_chime#1]
```
NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:76:in `controller_issues_after_save'
  plugins/redmine_dmsf/lib/redmine_dmsf/hooks/controllers/issues_controller_hooks.rb:52:in `controller_issues_edit_after_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  plugins/redmine_amazon_chime/lib/redmine_amazon_chime/issue_patch.rb:26:in `save_from_issue'
  app/models/issue.rb:210:in `create_or_update'
  app/controllers/issues_controller.rb:564:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:552:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:169:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
```

**Comment by tsz662** [comment]
Renamed hook methods.
